### ISSUE TITLE
Feature Request: Support for dependent jobs

### ISSUE THREAD

**Issue by bjartek** [vgarvardt/gue#121]
Have you considered supporting dependent jobs? I have not digged deep into the scheduler code of this project yet, but since there are configuration options to not run until a given time or run again on error I should belive it would be possible to add an option to

- check if a list of job_ids are fulfilled
- check that there are no pending jobs of the given job type
- check that there are no pending jobs in the given queue

My main use case for this is creating a workflow like this:

Job V1: Read a validate config.
Job P1-P3: In paralell run 3 different tasks
Job G1: Wait until P1-3 are done, generate a job list of hundres of jobs R
Job R1-Rx: Run all the jobs
Job P4: Wait until all R are done. Run another job 
Job G2: Wait until P4 is done. Generate yet more hundres of jobs of a different type S
Job S1-Sx: Run all the hundres of jobs
Job P5: wait until all S are done: Run a final job

In this case the queue for P, R, S is the same but the job type is different. Infact the job type for each P is different. (This queue runs transactions and need identity on the worker) the queue for G,V is the same and they only generate items do not do blockchain work.

All this is possible to just handle without support from the framework but it would results in lots of errors since for each time you want to schedule a job that is yet to run you have to Return an error, or I guess adjust it to check again in a couple of minutes. I approximately know how long each task takes here.

**Comment by vgarvardt** [comment]
What you're explaining sounds like Orchestration pattern. It is possible to use this library as a component for Orchestration implementation, but the library itself is not the right place to implement it - \\ this functionality is outside of the scope for the simple tasks scheduler.
