### ISSUE TITLE
Panic error messages only logged in database

### ISSUE THREAD

**Issue by deimantastumas** [vgarvardt/gue#125]
I've noticed that panic error messages are not outputted/logged and can only be checked in the database `last_error` column. I've tried debugging the code when panic is produced and the logger is indeed set to `NoOpLogger` in the recovery code scope:
<img width="851" alt="Screenshot 2022-11-13 at 19 23 42" src="https://user-images.githubusercontent.com/36602611/201535172-5d734be2-9cc3-4ee7-a5f9-6576f2e20a15.png">

Passing both `StdLogger` or `zap.Logger` when creating a gue client didn't help. Example of how I'm setting the custom logger:
```
gc, err := gue.NewClient(poolAdapter, gue.WithClientLogger(adapter.NewStdLogger()))
```

Is it the expected behavior and I've misunderstood how custom loggers should work or is it a bug?

I'm using `v4` gue version: `github.com/vgarvardt/gue/v4 v4.1.0`

**Comment by vgarvardt** [comment]
Covered this case with the test at https://github.com/vgarvardt/gue/pull/126 - works as expected, the log is there. Panic is handled by the worker as it is responsible for calling the handler, so you need to set logger to the `NewWorker()` or `NewWorkerPool()`

**Comment by deimantastumas** [comment]
Thanks for clarifying. The provided test helped a lot!
