### ISSUE TITLE
Way to distinguish between a 'successful' versus 'failed' job

### ISSUE THREAD

**Issue by gbl-tylers** [vgarvardt/gue#134]
The scenario I'm running into is this
* Spawn job to check if a transaction is valid, it may either be successful, failed, or not confirmed yet. 
* If its not confirmed, throw an error, so we can retry again later
* If its failed or successful, return nil to not retry, but then on a JobDone callback i want to distinguish between the successful or failed transaction

Is there a way to implement this behaviour in the library, or would I need to build something around the library instead?

**Comment by vgarvardt** [comment]
Hi @gbl-tylers,

This is not really possible as Job has only two states - finished with error or w/out error. Everything else is not related to the Job, but is domain-specific data that handler is doing.

But as of https://github.com/vgarvardt/gue/pull/131 (not released yet) it is possible to have a hacky third state using `ErrDiscardJob`. So in your case it could look like this:
- not confirmed - some error, worker will re-schedule the job to the later time
- successful - no error
- failed - error `ErrDiscardJob` will mark the job as not successful, but it will not be re-scheduled and in the hook you'll have a typed error, so you'll be able to distinguish between `not confirmed` and `failed` errors

**Comment by gbl-tylers** [comment]
Thanks, that's good to hear. In the future we will definitely be trying that fix, for now we found a solution to just to the transaction confirmation again after the job is finished, will close this ticket
