### ISSUE TITLE
Add maximum retry

### ISSUE THREAD

**Issue by cahyowhy** [vgarvardt/gue#149]
Is there a way to limit the called of worker function if those worker function its always return an `err` ?
something like how much retry operation that its need

**Comment by vgarvardt** [comment]
You can check how many times the job was already retried using `Job.ErrorCount` and return either `nil` to mark job as done, or [`ErrDiscardJob`](https://github.com/vgarvardt/gue/blob/master/error.go#L55) to mark job as done and log it as erorred to have information about this event in the log collector.

**Comment by cahyowhy** [comment]
nice 
thanks for this library and your suggestion 🙏🏻
