### ISSUE TITLE
Can't use more than 5 workers

### ISSUE THREAD

**Issue by sxwebdev** [vgarvardt/gue#170]
Can't use more than 5 workers

Can't use more than 5 workers. Gue client is blocked for unknown reasons

**Comment by vgarvardt** [comment]
Can you reproduce it with the test? What is your connection pool and DB settings - can be that you're running out of connections in the pool and all workers are not moving forward because of it.

**Comment by sxwebdev** [comment]
Yes, that was exactly the problem. I increased the number of connections in the postgres pool and it worked. Thank you
