### ISSUE TITLE
Postgres Listen/Notify instead of polling

### ISSUE THREAD

**Issue by Joker666** [vgarvardt/gue#171]
First of all great work. Works as expected with tonnes of options but I will just point out the obvious that came to my mind.

While the poll works great, Postgres's Listen/Notify interface offers more significant benefits. And in the Elixir world, there's a popular job processing package leveraging this to be much more scalable.

https://github.com/sorentwo/oban

Interestingly that project also offers paid licenses for more plugins and web UI. This package actually falls back to polling if for some reason pub/sub stops working.

Understandingly this is an open-source project but please consider this as an eventual path forward. I am open to collaborating on this.

https://getoban.pro/articles/one-million-jobs-a-minute-with-oban

**Comment by vgarvardt** [comment]
Thank you for your feedback.

Polling is the architectural decision that I made here for several reasons - it is much simpler and more error-prone. In the past I had experience working with Pg's Listen/Notify and ended up refactoring my solution to simple polling, so here it was only polling from the beginning and there are no plans to add Listen/Notify.

One of the developers contacted me regarding UI, I'm supporting him with some minor changes that I'm making to the library, maybe one day UI will become a thing.

In general I'm not very interested in making a Product from this library. I'm using it in couple products, it has its main purpose that it serves - maintain strong consistency.

**Comment by Joker666** [comment]
> it is much simpler and more error-prone

I think you meant less error-prone.

Can you elaborate on what was the main reason behind the refactoring of Listen/Notify? Was the implementation not stable or did it make the project more complex or any other possible reason?

**Comment by vgarvardt** [comment]
> I think you meant less error-prone.

yes, sure
