### ISSUE TITLE
Undesirable trace spans from poll function

### ISSUE THREAD

**Issue by markhildreth-gravity** [vgarvardt/gue#185]
We're using `gue` together with [Gorm](https://gorm.io/), and specifically the [`otelgorm`](https://pkg.go.dev/github.com/uptrace/opentelemetry-go-extra/otelgorm) library which provides otel spans when Gorm executes a SQL command.

The issue that we see is that because the [poll function occurs before the first span is emitted from gue](https://github.com/vgarvardt/gue/blob/10d839d75bffb1c95dd02d3f31a8efabb9dee701/worker.go#L183-L200), the span that ends up being emitted by the "poll" gorm call becomes its  own root span without any context about gue. For us, it would be desirable if the `gue` span includes the the poll query so that the poll is part of the worker span.

Of course, the downside of this switch is that any users of `gue` would start getting job spans for every poll, regardless of if the poll found a job. I could see how this could be undesirable.

Aside from an `IncludePollInTrace` option, not sure if there is a "good" solution to this.

**Comment by markhildreth-gravity** [comment]
@vgarvardt Thanks for looking into this.

Gorm was just an example. A better way to have said this is that I would like any traces/spans that occur during `w.pollFunc` to be included in the same span that is used for job processing. I've added some code [here](https://github.com/vgarvardt/gue/pull/186) to give you an example.

As mentioned, this means that every time a poll occurs, a span is created, which could be quite noisy, but at least those events/spans are not separated from the worker.

**Comment by vgarvardt** [comment]
Yes, now I got it, thx! You're right about the number of spans, I'll try to find if there is a simple way of "discarding" started span in case there were no job found, maybe simply omitting `span.End()` will be enough.

**Comment by vgarvardt** [comment]
Made a changed based on your PR - https://github.com/vgarvardt/gue/pull/187 - will test it a little bit more and if all good then will release it.

**Comment by vgarvardt** [comment]
Released in https://github.com/vgarvardt/gue/releases/tag/v5.2.1 - pls check

**Comment by markhildreth-gravity** [comment]
@vgarvardt This tested as working in my project. Thanks a bunch!
