### ISSUE TITLE
Database migration with an API and a worker

### ISSUE THREAD

**Issue by Icaro-Lima** [vgarvardt/gue#24]
Let's suppose that I have an API and a worker both using [gue](https://github.com/vgarvardt/gue), what approach do you recommend for migrating the database?

Some ways that I had been though:

1. The API migrate all models.
2. The API and the worker try to migrate on initialization.

For the 1st, I am worried about the execution order.
For the 2nd, I am thinking about the shared code to enable this.

**Comment by vgarvardt** [comment]
Can you please elaborate? I'm not sure what kind of migration you are talking about. Is it about applying B migration to create required DB table? Or data migration on your app? Or maybe something else?

**Comment by Icaro-Lima** [comment]
Ah, sorry, I am talking about DB migration to create the required table.

**Comment by vgarvardt** [comment]
Normally I use something like https://github.com/golang-migrate/migrate and run migrations on app bootstrap. It has lock inside, so when API and worker use the same db it is not a problem.
