### ISSUE TITLE
Hooks are not executing for jobs that panic

### ISSUE THREAD

**Issue by HTechHQ** [vgarvardt/gue#247]
Hi, I want to persist the start and end of a job in the same database row in a history table. For this I am using the hooks and can record the end time of jobs that return a normal error just fine.

Having jobs that panic does not work as expected, from the best I can tell the hooks registered with `WithPoolHooksJobDone` are not called at all in this case.

Version 5.5.0
Hooks registered via `WithPoolHooksJobLocked` are executed though.

**Comment by vgarvardt** [comment]
Tried to quickly fix this missed call in https://github.com/vgarvardt/gue/pull/249 but failed test reminded why this is not currently implemented - job done hook may also panic, so panic handler is not calling it as it is already in the process of recovery.

Will think how to implement it w/out adding too much complexity.

**Comment by HTechHQ** [comment]
Thank you!

**Comment by vgarvardt** [comment]
Should be fixed in https://github.com/vgarvardt/gue/releases/tag/v5.6.0

**Comment by HTechHQ** [comment]
The new version fixes it!

Thank you very much. You are an awesome maintainer!
