### ISSUE TITLE
Can't run `go mod tidy` after installing

### ISSUE THREAD

**Issue by zapo** [vgarvardt/gue#26]
It seems like pgx dependency points to a no longer available module.

```
github.com/vgarvardt/gue/v2 imports
        github.com/jackc/pgtype tested by
        github.com/jackc/pgtype.test imports
        github.com/jackc/pgx/v4 tested by
        github.com/jackc/pgx/v4.test imports
        github.com/jackc/pgtype/ext/satori-uuid: module github.com/jackc/pgtype@latest found (v1.6.1), but does not contain package github.com/jackc/pgtype/ext/satori-uuid

```
I was able to fix on my working copy by bumping pgx to latest.
```
-       github.com/jackc/pgx/v4 v4.0.0-pre1.0.20190824185557-6972a5742186
+       github.com/jackc/pgx/v4 v4.9.0
```

Let me know if you would like a PR for that. Tests still pass but I didn't test the functionality (since I'm not using that adapter).

**Comment by vgarvardt** [comment]
@zapo thank you for reporting. I just merged potential fix - can you please try version from master branch and if it works for you then I'll issue new release.

**Comment by zapo** [comment]
It works, thank you!
