### ISSUE TITLE
Keeping finished jobs in the database

### ISSUE THREAD

**Issue by rverton** [vgarvardt/gue#41]
Hi,
first of all thanks for this project, it's exactly what I was looking for.

I'm currently playing around with it and saw that finished jobs are removed afterwards from the table. Have you thought of adding an option to keep finished jobs in the database to get some sort of log?

robin

**Comment by vgarvardt** [comment]
Hi. Yes, I thought about it, but the idea of the project is to act like a simple queue implementation to replace RabbitMQ and other additional queue implementations for many simple cases where "execute and forget" is the desired strategy.

Keeping a log of operations is very specific task to be added as a general purpose solution. Although I'm thinking now about adding some sort of pre/post-processing hooks that may be used for logging implementation as well.

**Comment by rverton** [comment]
Sounds like a good idea. Thanks for responding.

**Comment by vgarvardt** [comment]
You can try it in https://github.com/vgarvardt/gue/releases/tag/v3.3.0

**Comment by rverton** [comment]
Awesome! I will give it a try later this day I think, thanks :)

**Comment by rverton** [comment]
Works great here, I think we can close this now.
