### ISSUE TITLE
Worker failed to lock a job

### ISSUE THREAD

**Issue by ljg-cqu** [vgarvardt/gue#47]
I encountered a  problem, why? Thank you for you answern.
Details:
[gue-logger.go:26::github.com/ljg-cqu/core/logger/adapter.(*gueAdapter).Debug()] Feb 23 19:09:36.946 [D] Tried to enqueue a job
[gue-logger.go:42::github.com/ljg-cqu/core/logger/adapter.(*gueAdapter).Error()] Feb 23 19:09:36.946 [E] Worker failed to lock a job
......
[gue-logger.go:42::github.com/ljg-cqu/core/logger/adapter.(*gueAdapter).Error()] Feb 23 19:09:46.954 [E] Worker failed to lock a job
[gue-logger.go:34::github.com/ljg-cqu/core/logger/adapter.(*gueAdapter).Info()] Feb 23 19:10:26.946 [I] Worker finished
[gue-logger.go:34::github.com/ljg-cqu/core/logger/adapter.(*gueAdapter).Info()] Feb 23 19:10:26.946 [I] Worker pool finished

**Comment by vgarvardt** [comment]
What logger adapter are you using? This error log message should have an original error in the context - https://github.com/vgarvardt/gue/blob/master/worker.go#L189

**Comment by ljg-cqu** [comment]
Sorry to reply late. My logger adapter is self-customized logurs.Logger. I have found the answer. 
The problem occurred just because of "SKIP LOCKED"  incompatability with Cockroachdb test server, 
which can be got from here: https://github.com/cockroachdb/cockroach-go/tree/master/testserver.

**Comment by vgarvardt** [comment]
The library designed to work and is tested only with PostgreSQL, not any other DB. It is possible that some Postgres-compatibale DBs may work, but they should be explicitly tested with some integration tests beforehand.
