### ISSUE TITLE
GRPC interface

### ISSUE THREAD

**Issue by metropolisenchanting** [vgarvardt/gue#63]
Hi, what do you think of a grpc interface? If I would build it would you accept a pull request?

**Comment by vgarvardt** [comment]
Can you pls explain what do you mean by this?

gRPC is the binary API protocol over http2 with messages encoded using Protobuf, and I do not get how it may relate to this library.

**Comment by vgarvardt** [comment]
I'm not sure it makes sense to add such functionality to this simple library. Sounds more like a service that can be built on top, using this library as one of the dependencies.

**Comment by metropolisenchanting** [comment]
okay thanks for your opinion
