### ISSUE TITLE
`HooksJobDone` are not executed within the transaction in case of a `WorkFunc` failure.

### ISSUE THREAD

**Issue by ab116699** [vgarvardt/gue#65]
In case a worker runs a `WorkFunc` that returns an error, `hooksJobDone` will not run within the same transaction because calling `op.Error()` defers a call to `op.Done()` which commits the transaction, see line 232 in `worker.go`.

 https://github.com/vgarvardt/gue/blob/859d3f25336ce554b81881a585f1b9ab7644fc68/worker.go#L232

One solution would be to remove the `defer job.Done()` from `job.Error()`, since `worker.go` already defers `j.Done()` :

1. it will ensure the transaction is committed 
2. hooks that use the transaction will properly execute.

A Second backwards-compatible solution would be to add a `alwaysDone` flag to `Job` type which will conditionally run the defer block in https://github.com/vgarvardt/gue/blob/859d3f25336ce554b81881a585f1b9ab7644fc68/job.go#L133 .

The example hook in the readme will break if the `WorkerFunc` returns an error.

**Comment by vgarvardt** [comment]
Thank you for reporting. I could reproduce the issue with the test and fixed it by calling hooks before calling `Error` handler. You can check details at https://github.com/vgarvardt/gue/pull/66

Released fix in https://github.com/vgarvardt/gue/releases/tag/v4.0.0-alpha.9 - pls check

**Comment by ab116699** [comment]
Thank you for the quick reply, fix seems good.
